name: Publish base image

on:
  push:
    branches: [master]
    paths:
      - base/**
  workflow_dispatch:

jobs:
  publish:
    if: github.ref == 'refs/heads/master'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-base.yml
    with:
      push: true
      platforms: linux/amd64,linux/arm64
    secrets: inherit
