name: Validate base image

on:
  pull_request:
    paths:
      - base/**

permissions:
  contents: read
  packages: read

jobs:
  validate:
    uses: ./.github/workflows/_build-base.yml
    with:
      push: false
      platforms: linux/amd64
